apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
resources:
  - namespace.yaml
  - database.yaml
  - database-serviceaccount.yaml
  - temporal-kustomization.yaml
  - dashboards
  - alerts.yaml
