---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: epp--preview
  labels:
    app_name: epp
    app_env: epp--preview

spec:
  interval: 1m
  releaseName: mongodb
  chart:
    spec:
      chart: psmdb-db
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: db-operator-system
      interval: 1m

  values:
    allowUnsafeConfigurations: true
    sharding:
      enabled: false
      configsvrReplSet:
        size: 1
    backup:
      enabled: false
    replsets:
    - name: rs0
      size: 1
      configuration: |
        systemLog:
          verbosity: 0
          quiet: true
      antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        maxUnavailable: 1
      expose:
        enabled: false
        exposeType: ClusterIP
      nonvoting:
        enabled: false
        size: 1
        antiAffinityTopologyKey: "kubernetes.io/hostname"
        podDisruptionBudget:
          maxUnavailable: 1
        resources:
          limits:
            cpu: "300m"
            memory: "0.5G"
          requests:
            cpu: "300m"
            memory: "0.5G"
        volumeSpec:
          emptyDir: {}
      arbiter:
        enabled: false
        size: 1
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
        requests:
          cpu: "300m"
          memory: "0.5G"
      volumeSpec:
        emptyDir: {}
