apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: epp--migration-test
  namespace: epp--migration-test
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/apps/epp
  prune: true
  targetNamespace: epp--migration-test
  images:
    - name: ghcr.io/elifesciences/enhanced-preprints-server
      newTag: master-69f2336a-20231220.1535 # {"$imagepolicy": "epp--migration-test:epp-server:tag"}
    - name: ghcr.io/elifesciences/epp-image-server
      newTag: master-a34dfaa2-20231003.1350 # {"$imagepolicy": "epp--migration-test:epp-image-server:tag"}
    - name: ghcr.io/elifesciences/enhanced-preprints-client
      newTag: master-744c5c4a-20231220.1649 # {"$imagepolicy": "epp--migration-test:epp-client:tag"}
    - name: ghcr.io/elifesciences/enhanced-preprints-storybook
      newTag: master-744c5c4a-20231220.1649 # {"$imagepolicy": "epp--migration-test:epp-storybook:tag"}
    - name: ghcr.io/elifesciences/enhanced-preprints-import-worker
      newTag: master-c01cfb09-20231220.1643 # {"$imagepolicy": "epp--migration-test:epp-import:tag"}
    - name: ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api
      newTag: master-39fa50ec-20231220.1532 # {"$imagepolicy": "epp--migration-test:epp-biorxiv-xslt-api:tag"}
  postBuild:
    substitute:
      app_env: migration-test
      app_hostname: migration-test--epp.elifesciences.org
      data_hub_api: https://data-hub-api.elifesciences.org/enhanced-preprints/docmaps/v2/by-publisher/elife/get-by-manuscript-id?manuscript_id=
      storybook_hostname: migration-test--epp-storybook.elifesciences.org
      journal_api_hostname: migration-test--epp-api.elifesciences.org
      iiif_server: https://migration-test--epp.elifesciences.org/iiif
      image_server_source_base_url: https://github.com/elifesciences/enhanced-preprints-data/raw/master/data/
      mongodb_hostname: epp-database-psmdb-db-replicaset
      mongodb_secret_name: epp-database-psmdb-db-secrets
      mongodb_secret_user_key: MONGODB_DATABASE_ADMIN_USER
      mongodb_secret_pass_key: MONGODB_DATABASE_ADMIN_PASSWORD
      client_replicas: "1"
      server_replicas: "1"
      s3_bucket: migration-test-elife-epp-data
      image_server_source_static: S3Source
      image_server_s3_bucket: migration-test-elife-epp-data
      image_server_role_arn: arn:aws:iam::512686554592:role/epp-migration-test-image-server
      epp_server_role_arn: arn:aws:iam::512686554592:role/epp-migration-test-epp-server
      epp_server: http://epp-server:3000
      temporal_server: temporal-frontend.temporal:7233
      temporal_namespace: epp--migration-test
      import_role_arn: arn:aws:iam::512686554592:role/epp-migration-test-import
      disallow_robots: all
      worker_import_docmaps_queue_replicas: "0"
      worker_epp_queue_replicas: "0"
      biorxiv_xslt_api_replicas: "0"
