apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo--prod
  namespace: podinfo--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/apps/podinfo
  prune: true
  targetNamespace: podinfo--prod
  images:
  - name: docker.io/stefanprodan/podinfo
    newTag: 6.7.0 # {"$imagepolicy": "podinfo--prod:podinfo-stable:tag"}
  postBuild:
    substitute:
      hostname: podinfo.elifesciences.org
  patches:
  - target:
      kind: Ingress
      name: podinfo
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: podinfo
        namespace: podinfo
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://oauth-proxy.elifesciences.org/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth-proxy.elifesciences.org/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
