apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: epp-biorxiv-xslt-api
  namespace: epp
spec:
  interval: 5m
  image: ghcr.io/elifesciences/enhanced-preprints-biorxiv-xslt-api
