---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds

spec:
  interval: 5m
  releaseName: prometheus-operator-crds
  chart:
    spec:
      chart:  prometheus-operator-crds
      version: 26.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  upgrade:
    crds: CreateReplace
