apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo--prod
  namespace: podinfo
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kustomizations/apps/podinfo
  prune: true
  targetNamespace: podinfo
  images:
  - name: docker.io/stefanprodan/podinfo
    newTag: 6.9.4 # {"$imagepolicy": "podinfo:podinfo-stable:tag"}
  postBuild:
    substitute:
      hostname: podinfo.${cluster_domain}
