apiVersion: apps/v1
kind: Deployment
metadata:
  name: epp-import-worker-docmaps
  namespace: epp
spec:
  replicas: ${worker_import_docmaps_queue_replicas:=1}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: epp-import
      task_queue: import-docmaps
  template:
    metadata:
      namespace: epp
      labels:
        app: epp-import
        task_queue: import-docmaps
    spec:
      serviceAccountName: epp-import
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: epp-import
        image: ghcr.io/elifesciences/enhanced-preprints-import-worker:latest
        resources:
          requests:
            memory: ${worker_memory_requests:='3Gi'}
            cpu: ${worker_cpu_requests:='500m'}
          limits:
            memory: ${worker_memory_limits:='4Gi'}
            cpu: ${worker_cpu_limits:='1500m'}
        env:
        - name: BUCKET_NAME
          value: ${s3_bucket}
        - name: EPP_SERVER_URI
          value: ${epp_server}
        - name: TEMPORAL_SERVER
          value: ${temporal_server}
        - name: XSLT_TRANSFORM_ADDRESS
          value: http://epp-biorxiv-xslt-api:80
        - name: TEMPORAL_TASK_QUEUE
          value: import-docmaps
        - name: TEMPORAL_NAMESPACE
          value: "${temporal_namespace}"
        - name: TEMPORAL_MAX_CONCURRENT_ACTIVITY_TASK_EXECUTIONS
          value: "${temporal_max_concurrent_activity_task_executions:='25'}"
        - name: TEMPORAL_MAX_CONCURRENT_WORKFLOW_TASK_EXECUTIONS
          value: "${temporal_max_concurrent_workflow_task_executions:='5'}"
        - name: TEMPORAL_MAX_CACHED_WORKFLOWS
          value: "${temporal_max_cached_workflows:='5'}"
        ports:
          - containerPort: 9464
