apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- namespace.yaml
- source.yaml
- release.yaml
- global-middlewares/compress.yaml
- global-middlewares/elife-oauth.yaml
- global-middlewares/redirect-www-to-non-www.yaml
- global-middlewares/mitigate-cve-2025-64459.yaml
- global-middlewares/deny-robots.yaml
- global-middlewares/ping.yaml

configMapGenerator:
- name: traefik-dashboards
  files:
    - dashboards/Traefik-Official-Standalone-Dashboard.json
  options:
    labels:
      grafana_dashboard: "1"
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: "disabled"
