apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 39.0.0
  interval: 1h0m0s
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
        fields:
          headers:
            defaultmode: drop
            names:
              # Specific custom headers
              x-ja4fingerprint: keep
              X-Forwarded-For: keep
              X-Original-Forwarded-For: keep
              X-Forwarded-Host: keep

              # Standard headers
              User-Agent: keep
              Referer: keep

              # Useful for tracking
              X-Request-ID: keep
    deployment:
      replicas: 10
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
    ingressClass:
      name: traefik
      enabled: true
      isDefaultClass: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        ingressClass: traefik
        enabled: true
        allowEmptyServices: true
        allowExternalNameServices: true
    ingressRoute:
      dashboard:
        enabled: true #only on traefik entrypoint
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    ports:
      web:
        http:
          encodedCharacters:
            allowEncodedSlash: true
          middlewares:
            - traefik-compress@kubernetescrd
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/16"
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/16"
            - "88.97.165.112/32"
      websecure:
        http:
          encodedCharacters:
            allowEncodedSlash: true
          middlewares:
            - traefik-compress@kubernetescrd
        proxyProtocol:
          trustedIPs:
            - "10.0.0.0/16"
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/16"
            - "88.97.165.112/32"
    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
    experimental:
      plugins:
        inlineResponse:
          moduleName: github.com/tuxgal/traefik_inline_response
          version: v0.1.2
        traefikerrorreplace:
          moduleName: github.com/PseudoResonance/traefikerrorreplace
          version: v1.0.1
        htransformation:
          moduleName: "github.com/tomMoulard/htransformation"
          version: "v0.3.3"
