---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elife-oauth-auth
  namespace: traefik
spec:
  forwardAuth:
    address: "https://${oauth2_proxy_hostname}/oauth2/auth"
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
      - "Set-Cookie"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elife-oauth-signin
  namespace: traefik
spec:
  errors:
    status:
      - "401"
    service:
      name: infra-oauth2-proxy
      namespace: infra
      port: 80
    query: "/oauth2/start?rd={url}"
    statusRewrites:
      "401": 302
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elife-oauth
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: elife-oauth-signin
      - name: elife-oauth-auth
