---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ping-fastly
  namespace: traefik
spec:
  plugin:
    inlineResponse:
      matchers:
        - path:
            abs: /ping-fastly
          statusCode: 200
          response:
            raw: pong
