---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www-to-non-www
  namespace: traefik
spec:
  redirectRegex:
    regex: "^https?://www\\.(.*)"
    replacement: "https://$${1}"
    permanent: true
