apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storageclass.yaml
- volumesnapshotclass.yaml
- al2023nodeclass.yaml
- nodepool.yaml
- nodepool-services.yaml
- deployment-sync.yaml
