apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: basex-validator
resources:
- automations/basex-validator-policy.yaml
- automations/basex-validator-source.yaml
- service.yaml
- deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/component: basex-validator
  app.kubernetes.io/instance: basex-validator--${env}
  app.kubernetes.io/name: basex-validator
