apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storageclasses
- volumeattributeclasses
- volumesnapshotclasses
- secret-store
- ../base
- ../../aws-load-balancer-controller
