---
# Source: temporal/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::512686554592:role/elife-temporal-prod
