gcpProjectName: "elife-data-pipeline"
importedTimestampFieldName: "imported_timestamp"
stateFile:
  defaultBucketName: "{ENV}-elife-data-pipeline"
  defaultSystemGeneratedObjectPrefix: "airflow-config/{ENV}-s3-csv/state/s3-csv"

defaultConfig:
  airflow:
    dagParameters:
      schedule: '*/30 * * * *'  # At every 30th minute
      tags:
        - 'CSV'

s3Csv:
  - dataPipelineId: rp_reviews_and_elife_assessment_emails
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataHub:_RP_Reviews_and_eLife_Assessment_Emails_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: rp_reviews_and_elife_assessment_emails
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/rp_reviews_and_elife_assessment_emails_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: ejp_manuscript_version_notes
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataHub:_Manuscript_Version_Notes_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: ejp_manuscript_version_notes
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/ejp_manuscript_version_notes_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: manuscript_license
    description: 
      For DocMaps
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataHub:_Manuscript_License_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: manuscript_license
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/manuscript_license_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: 767_datascience_person_roles_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_Person_Roles_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: 767_datascience_person_roles
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/767_datascience_person_roles_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: 779_datascience_reviewer_info_all_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_Reviewer_info_-_all_*_eLife.csv
      - ejp_query_tool_query_id_DataScience:_Reviewer_info_-_last_week_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: 779_datascience_reviewer_info_all
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/779_datascience_reviewer_info_all_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: editorial_manuscript_consultation_session_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_Consultation_Sessions_-_all_*_eLife.csv
      - ejp_query_tool_query_id_DataScience:_Consultation_Sessions_-_last_week_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: editorial_manuscript_consultation_session
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/editorial_manuscript_consultation_session_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: 380_datascience_early_career_researchers_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_Early_Career_Researchers_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: 380_datascience_early_career_researchers
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/380_datascience_early_career_researchers_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: 489_datascience_editor_keywords_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_Editor_Keywords_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: 489_datascience_editor_keywords
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/489_datascience_editor_keywords_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: datascience_etoc_content_subscribers_last_week_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_DataScience:_eToc_Content_Subscribers_-_all_*_eLife.csv
      - ejp_query_tool_query_id_DataScience:_eToc_Content_Subscribers_-_last_week_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: datascience_etoc_content_subscribers_last_week
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/datascience_etoc_content_subscribers_last_week_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1
    recordProcessingSteps:
      - html_unescape

  - dataPipelineId: prod_ejp_data_export_date_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_Production_Data:_Export_dates_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: prod_ejp_data_export_date
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_ejp_data_export_date_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1

  - dataPipelineId: prod_ejp_feature_templates_001
    bucketName: elife-ejp-ftp
    objectKeyPattern:
      - ejp_query_tool_query_id_Production_Data:_Feature_templates_*_eLife.csv
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: prod_ejp_feature_templates
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_ejp_feature_templates_001.json"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: date_generated_info
        metadataLineIndex: 1

  - dataPipelineId: prod_task_adept_timer_report_range_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-task-adept
    objectKeyPattern:
      - Timer_Report_Range_for_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_task_adept_timer_report_range
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_task_adept_timer_report_range_001.json"

  - dataPipelineId: prod_task_adept_carina_eol_kriya_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-task-adept
    objectKeyPattern:
      - Carina_EOL_Kriya_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_task_adept_carina_eol_kriya
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_task_adept_carina_eol_kriya_001.json"

  - dataPipelineId: prod_task_adept_carina_eol_elife_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-task-adept
    objectKeyPattern:
      - Carina_EOL_eLife_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_task_adept_carina_eol_elife
    tableWriteAppend: True
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_task_adept_carina_eol_elife_001.json"

  - dataPipelineId: prod_kriya_digest_sub_article_info_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - Digest_Sub-article_Info_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_digest_sub_article_info
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_digest_sub_article_info_001.json"

  - dataPipelineId: prod_kriya_press_info_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - Press_Info_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_press_info
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_press_info_001.json"

  - dataPipelineId: prod_kriya_published_stage_history_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - Published_Stage_History_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_published_stage_history
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_published_stage_history_001.json"

  - dataPipelineId: prod_kriya_published_stage_summary_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - Published_Stage_Summary_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_published_stage_summary
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_published_stage_summary_001.json"

  - dataPipelineId: prod_kriya_wip_stage_summary_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - WIP_Stage_Summary_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_wip_stage_summary
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_wip_stage_summary_001.json"

  - dataPipelineId: prod_kriya_wip_stage_history_001
    description:
      For Production Team
    airflow:
      dagParameters:
        schedule: "@daily"
    bucketName: prod-elife-kriya
    objectKeyPattern:
      - WIP_Stage_History_*
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: prod_kriya_wip_stage_history
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/prod_kriya_wip_stage_history_001.json"

  - dataPipelineId: sciety_events
    description:
      Load Sciety Events from CSV to BigQuery.
      Parse "payload" as JSON.
    bucketName: sciety-data-extractions
    objectKeyPattern:
      - sciety--prod--events-from-cronjob.csv
    headerLineIndex: 0
    dataValuesStartLineIndex: 1
    datasetName: "{ENV}"
    tableName: 'sciety_event'
    tableWriteAppend: False
    stateFile:
      bucketName: "{ENV}-elife-data-pipeline"
      objectName: "airflow-config/s3-csv/{ENV}-state/sciety_events.json"
    recordProcessingSteps:
      - parse_json_value
    airflow:
      taskParameters:
        queue: 'kubernetes'
        executor_config:
          pod_override:
            spec:
              containers:
                - name: 'base'
                  resources:
                    limits:
                      memory: 1Gi
                      cpu: 1000m
                    requests:
                      memory: 1Gi
                      cpu: 100m
