gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: "imported_timestamp"
spreadsheets:
    # this is the public editor profile
  - spreadsheetId: "1VnpuiY3o4iCEIEWjCKfXFFyowxTfTxzno2VU5UnRINE"
    sheets:
      - sheetName: 'BREs'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'public_editor_profile'
        tableWriteAppend: True
        fixedSheetRecordMetadata:
          - metadataSchemaFieldName: 'editor_role'
            fixedSheetValue: "bre"

      - sheetName: 'Senior Editors'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'public_editor_profile'
        tableWriteAppend: True
        fixedSheetRecordMetadata:
          - metadataSchemaFieldName: 'editor_role'
            fixedSheetValue: "senior editor"

  - spreadsheetId: '1nQcLBO_yIumkXousRg_-l9Kx1HmiG7NcvDg1vkrdK-0'
    sheets:
      - sheetName: 'BRE distribution_current'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'BRE_Distribution'
        tableWriteAppend: True
        #inSheetRecordMetadata:
        #  - metadataSchemaFieldName: 'metadata_example'
        #    metadataLineIndex: 1

  # unmatched manuscripts and override hypothesis matching
  - spreadsheetId: '15QcK8w-ssB7109RQEDtFpJPZ0J5HTGxoHa_2TtpMBbg'
    sheets:
      - sheetName: 'unmatched_list'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'unmatched_manuscripts'
        tableWriteAppend: true

      - sheetName: 'override_hypothesis_matching'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'override_hypothesis_matching'
        tableWriteAppend: true

  # deleted hypothesis annotations
  - spreadsheetId: '1naXfcCxvTC8fLPhR8K1znC9B5DMxGP7HMpp-2CcO_sY'
    sheets:
      - sheetName: 'deleted_hypothesis_list'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'deleted_hypothesis_annotations'
        tableWriteAppend: true

  # reviewed preprint publication date
  - spreadsheetId: '1amAlKvdLcaDp5W8Z8g77NmkwbMF5n_u89ArSqPMO8jg'
    sheets:
      - sheetName: 'publication_date'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'reviewed_preprint_publication_date'
        tableWriteAppend: true

  # meca path update
  - spreadsheetId: '1mctCQuNFBjSn97Lihy7_vBO6z7-N-oqyLv4clyi6zHg'
    sheets:
      - sheetName: 'meca_path'
        sheetRange: ''
        headerLineIndex: 0
        dataValuesStartLineIndex: 1
        datasetName: "{ENV}"
        tableName: 'reviewed_preprint_meca_path_update'
        tableWriteAppend: true
