---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: epp-image-server
  namespace: epp
spec:
  imageRepositoryRef:
    name: epp-image-server
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)-approved$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
